# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.network :private_network, ip: "192.168.56.66"
  config.vm.hostname = "solr.test"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end

  # Shell provisioner
  config.vm.provision "shell", inline: <<-SHELL

    echo "ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBACQxqzWcL9wRa56olYvlVa2S0A2oNtK9YX/nfcLtbKc8TdQRShJ2NOzfOcAqIrdfmVTxutMO5zC6Shguuo319m0YAB73A6tI3mcoJlM4ekFh7m/KzGLHqJh3ucpuoeY9iWmh5R47RBhRYqLpriti431Nt/fRJ0PHVvsyUFdhAgEzz9e9g== tchedem@kali" >> /home/vagrant/.ssh/authorized_keys

  SHELL

  # Ansible provisioner.
  config.vm.provision :ansible do |ansible|

    ansible.playbook = "provisioning/playbook.yml"

  end
end
