Vagrant.configure("2") do |config|
  
  config.vm.box = "debian/bullseye64"
  config.vm.network :private_network, ip: "192.168.56.9"
  config.vm.hostname = "hostname"
  config.ssh.insert_key = true
  
  config.vm.box_check_update = false

  config.vm.synced_folder "./", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    
    vb.gui = false

    vb.name = "ansible_meilisearch_vm"
    
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # I write a python script that you can use to do this simply
    echo "your_private_key_content" >> /home/vagrant/.ssh/authorized_keys
  SHELL
end
